# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy

builds:
  - main: ./cmd/webhook-deploy/
    env:
      - CGO_ENABLED=0
      - GOEXPERIMENT=jsonv2
    goos:
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - formats: [tar.gz]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: [zip]

nfpms:
  - id: webhook-deploy-deb-rpm
    package_name: webhook-deploy
    maintainer: "JDinABox <git@jdinabox.com>"
    description: "A webhook server to automatically deploy GitHub repositories."
    homepage: "https://github.com/JDinABox/webhook-deploy"
    license: "MIT"
    formats:
      - rpm
      - deb
    bindir: /usr/bin
    contents:
      - src: ./scripts/webhook-deploy.service
        dst: /etc/systemd/system/webhook-deploy.service
        file_info:
          mode: 0644
      - src: ./config/config.yaml
        dst: /etc/webhook-deploy/config.yaml
        type: config
        file_info:
          mode: 0644
      - dst: /var/log/webhook-deploy
        type: dir
        file_info:
          mode: 0755
    scripts:
      preinstall: "./scripts/preinstall.sh"
      postinstall: "./scripts/postinstall.sh"
      preremove: "./scripts/preremove.sh"
      postremove: "./scripts/postremove.sh"
  - id: webhook-deploy-apk
    package_name: webhook-deploy
    maintainer: "JDinABox <git@jdinabox.com>"
    description: "A webhook server to automatically deploy GitHub repositories."
    homepage: "https://github.com/JDinABox/webhook-deploy"
    license: "MIT"
    formats:
      - apk
    bindir: /usr/bin
    contents:
      - src: ./scripts/webhook-deploy.openrc
        dst: /etc/init.d/webhook-deploy
        file_info:
          mode: 0755
      - src: ./config/config.yaml
        dst: /etc/webhook-deploy/config.yaml
        type: config
      - dst: /var/log/webhook-deploy
        type: dir
        file_info:
          mode: 0755
    scripts:
      preinstall: "./scripts/preinstall.sh"
      postinstall: "./scripts/postinstall.sh"
      preremove: "./scripts/preremove.sh"
      postremove: "./scripts/postremove.sh"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
