listen: ":8080"
web-interface:
  enabled: true
  listen: "127.0.0.1:9080"
  username: "admin"
  password: "password"
deployments:
  JDinABox/webhook-deploy:
    secret: ""
    commands:
      - "go build ./cmd/webhook-deploy"
